/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agendamentos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class EmitirPrescricao extends javax.swing.JFrame {

    /**
     * Creates new form EmitirPrescricao
     */
    public EmitirPrescricao() {
        initComponents();
    }

    private void atualizarListaConsultas() {
    String crmMedico = crm.getText();
    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        conn = ConexaoBanco.getConnection();
        
        String sql = "SELECT c.id_consulta as id, c.data as data, e.nome AS especialidade " +
                     "FROM consulta c " +
                     "JOIN contrato ct ON c.id_contrato = ct.id_contrato " +
                     "JOIN medico m ON ct.id_medico = m.id_medico " +
                     "JOIN especialidade e ON ct.id_especialidade = e.id_especialidade " +
                     "WHERE c.status = 'Realizada' and m.crm = ?";
        stmt = conn.prepareStatement(sql);
        stmt.setString(1, crmMedico);
        rs = stmt.executeQuery();
        
        listaConsulta.removeAllItems(); // Limpa o JComboBox antes de adicionar novos itens
        
       if (!rs.isBeforeFirst()) { // Verifica se o ResultSet está vazio
            JOptionPane.showMessageDialog(this, "Nenhuma consulta realizada encontrada", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            while (rs.next()) {
                String id = rs.getString("id");
                String dataConsulta = rs.getString("data");
                String especialidade = rs.getString("especialidade");
                listaConsulta.addItem(id + ": " + dataConsulta + " - " + especialidade);
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar consultas: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Fecha a conexão e o PreparedStatement
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            System.out.println("Erro ao fechar a conexão: " + ex.getMessage());
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emitirPrescricao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        crm = new javax.swing.JTextField();
        listaConsulta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emitirPrescricao.setText("Emitir Prescrição");
        emitirPrescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitirPrescricaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Insira seu CRM");

        crm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crmActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione consulta realizada");

        jLabel3.setText("Descrição da Prescrição");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(descricao)
                            .addComponent(listaConsulta, 0, 231, Short.MAX_VALUE)
                            .addComponent(crm)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(emitirPrescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(emitirPrescricao)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emitirPrescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitirPrescricaoActionPerformed
        String crmMedico = crm.getText();
        String consultaSelecionada = (String) listaConsulta.getSelectedItem();
        String descricaoPrescricao = descricao.getText();

    if (consultaSelecionada == null || descricaoPrescricao.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione uma consulta e insira a requisição.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Extrair o ID da consulta da seleção
    String[] partes = consultaSelecionada.split(": ");
    int idConsulta = Integer.parseInt(partes[0]); // O ID da consulta é a primeira parte

    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        conn = ConexaoBanco.getConnection();
        
        // Inserir o pedido de exame e obter o ID gerado
        String sqlPedidoExame = "INSERT INTO prescricao (id_consulta, descricao, data) VALUES (?, ?, now())";
        stmt = conn.prepareStatement(sqlPedidoExame, PreparedStatement.RETURN_GENERATED_KEYS);
        stmt.setInt(1, idConsulta);
        stmt.setString(2, descricaoPrescricao);
        stmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Prescrição emitida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao emitir prescrição: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Fecha a conexão e os PreparedStatements
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        } catch (SQLException ex) {
            System.out.println("Erro ao fechar a conexão: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_emitirPrescricaoActionPerformed

    private void crmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmActionPerformed
        atualizarListaConsultas();
    }//GEN-LAST:event_crmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DashboardMedico.voltar();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmitirPrescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmitirPrescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmitirPrescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmitirPrescricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmitirPrescricao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crm;
    private javax.swing.JTextField descricao;
    private javax.swing.JButton emitirPrescricao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> listaConsulta;
    // End of variables declaration//GEN-END:variables
}
